CREATED ON: 2025-06-01 17:47:34||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\apis\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: post||LINE NO: 85||MESSAGE: USER SIGN IN API VIEW : POST - JSON parse error - Expecting ',' delimiter: line 3 column 5 (char 34)
CREATED ON: 2025-06-07 17:00:10||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\functions\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: signin_function||LINE NO: 64||MESSAGE: CONTACTS - FUNCTION HELPER - USER SIGNIN - [Errno 2] No such file or directory: 'users.csv'
CREATED ON: 2025-06-07 17:00:10||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\apis\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: post||LINE NO: 85||MESSAGE: USER SIGN IN API VIEW : POST - Internal Server Error
CREATED ON: 2025-06-07 17:27:09||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\functions\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: signin_function||LINE NO: 93||MESSAGE: CONTACTS - FUNCTION HELPER - USER SIGNIN - 'user_type'
CREATED ON: 2025-06-07 17:27:09||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\apis\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: post||LINE NO: 85||MESSAGE: USER SIGN IN API VIEW : POST - Internal Server Error
CREATED ON: 2025-06-07 18:04:06||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\functions\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: signin_function||LINE NO: 134||MESSAGE: CONTACTS - FUNCTION HELPER - USER SIGNIN - 'email_id'
CREATED ON: 2025-06-07 18:04:06||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\apis\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: post||LINE NO: 85||MESSAGE: USER SIGN IN API VIEW : POST - Internal Server Error
CREATED ON: 2025-06-07 18:04:29||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\functions\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: signin_function||LINE NO: 133||MESSAGE: CONTACTS - FUNCTION HELPER - USER SIGNIN - 'email_id'
CREATED ON: 2025-06-07 18:04:29||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\apis\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: post||LINE NO: 85||MESSAGE: USER SIGN IN API VIEW : POST - Internal Server Error
CREATED ON: 2025-06-07 18:08:12||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\functions\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: signin_function||LINE NO: 133||MESSAGE: CONTACTS - FUNCTION HELPER - USER SIGNIN - 'email_id'
CREATED ON: 2025-06-07 18:08:12||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\apis\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: post||LINE NO: 85||MESSAGE: USER SIGN IN API VIEW : POST - Internal Server Error
CREATED ON: 2025-06-07 18:08:42||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\functions\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: signin_function||LINE NO: 133||MESSAGE: CONTACTS - FUNCTION HELPER - USER SIGNIN - 'email_id'
CREATED ON: 2025-06-07 18:08:42||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\apis\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: post||LINE NO: 85||MESSAGE: USER SIGN IN API VIEW : POST - Internal Server Error
CREATED ON: 2025-06-07 18:08:44||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\functions\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: signin_function||LINE NO: 133||MESSAGE: CONTACTS - FUNCTION HELPER - USER SIGNIN - 'email_id'
CREATED ON: 2025-06-07 18:08:44||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\apis\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: post||LINE NO: 85||MESSAGE: USER SIGN IN API VIEW : POST - Internal Server Error
CREATED ON: 2025-06-07 18:09:39||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\functions\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: signin_function||LINE NO: 135||MESSAGE: CONTACTS - FUNCTION HELPER - USER SIGNIN - 'email_id'
CREATED ON: 2025-06-07 18:09:39||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\apis\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: post||LINE NO: 85||MESSAGE: USER SIGN IN API VIEW : POST - Internal Server Error
CREATED ON: 2025-06-07 18:09:47||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\functions\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: signin_function||LINE NO: 135||MESSAGE: CONTACTS - FUNCTION HELPER - USER SIGNIN - 'email_id'
CREATED ON: 2025-06-07 18:09:47||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\apis\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: post||LINE NO: 85||MESSAGE: USER SIGN IN API VIEW : POST - Internal Server Error
CREATED ON: 2025-06-07 18:11:06||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\functions\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: signin_function||LINE NO: 135||MESSAGE: CONTACTS - FUNCTION HELPER - USER SIGNIN - 'email_id'
CREATED ON: 2025-06-07 18:11:06||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\apis\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: post||LINE NO: 85||MESSAGE: USER SIGN IN API VIEW : POST - Internal Server Error
CREATED ON: 2025-06-07 18:12:28||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\functions\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: signin_function||LINE NO: 135||MESSAGE: CONTACTS - FUNCTION HELPER - USER SIGNIN - 'email_id'
CREATED ON: 2025-06-07 18:12:28||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\apis\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: post||LINE NO: 85||MESSAGE: USER SIGN IN API VIEW : POST - Internal Server Error
CREATED ON: 2025-06-07 18:17:00||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\functions\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: signin_function||LINE NO: 117||MESSAGE: CONTACTS - FUNCTION HELPER - USER SIGNIN - 'email_id'
CREATED ON: 2025-06-07 18:17:00||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\apis\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: post||LINE NO: 85||MESSAGE: USER SIGN IN API VIEW : POST - Internal Server Error
CREATED ON: 2025-06-07 18:19:45||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\functions\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: signin_function||LINE NO: 124||MESSAGE: CONTACTS - FUNCTION HELPER - USER SIGNIN - 'email_id'
CREATED ON: 2025-06-07 18:19:45||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\apis\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: post||LINE NO: 85||MESSAGE: USER SIGN IN API VIEW : POST - Internal Server Error
CREATED ON: 2025-06-07 18:22:53||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\functions\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: signin_function||LINE NO: 113||MESSAGE: CONTACTS - FUNCTION HELPER - USER SIGNIN - If using all scalar values, you must pass an index
CREATED ON: 2025-06-07 18:22:53||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\apis\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: post||LINE NO: 85||MESSAGE: USER SIGN IN API VIEW : POST - Internal Server Error
CREATED ON: 2025-06-07 18:23:57||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\functions\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: signin_function||LINE NO: 113||MESSAGE: CONTACTS - FUNCTION HELPER - USER SIGNIN - If using all scalar values, you must pass an index
CREATED ON: 2025-06-07 18:23:57||LEVEL: ERROR||LOGGER: contacts||PATH: C:\amit\work websites\django_medicare\contacts\apis\signin.py||FILE NAME: signin.py||MODULE: signin||FUNCTION NAME: post||LINE NO: 85||MESSAGE: USER SIGN IN API VIEW : POST - Internal Server Error
